# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: codex/messages/v1/catalog.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63odex/messages/v1/catalog.proto\x12\x11\x63odex.messages.v1\"2\n\x0bPostCreated\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x12\n\ncreated_at\x18\x02 \x01(\t\">\n\x0bTagsChanged\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\r\n\x05\x61\x64\x64\x65\x64\x18\x02 \x03(\t\x12\x0f\n\x07removed\x18\x03 \x03(\t\"0\n\nPostPurged\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x11\n\tpurged_at\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'codex.messages.v1.catalog_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POSTCREATED']._serialized_start=54
  _globals['_POSTCREATED']._serialized_end=104
  _globals['_TAGSCHANGED']._serialized_start=106
  _globals['_TAGSCHANGED']._serialized_end=168
  _globals['_POSTPURGED']._serialized_start=170
  _globals['_POSTPURGED']._serialized_end=218
# @@protoc_insertion_point(module_scope)
