# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: codex/messages/v1/media.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63odex/messages/v1/media.proto\x12\x11\x63odex.messages.v1\"+\n\tObjectRef\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x0e\n\x06object\x18\x02 \x01(\t\"\x98\x01\n\x0fProcessMediaJob\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0f\n\x07post_id\x18\x02 \x01(\t\x12,\n\x06source\x18\x03 \x01(\x0b\x32\x1c.codex.messages.v1.ObjectRef\x12\x12\n\nmedia_type\x18\x04 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x05 \x01(\t\x12\x0c\n\x04want\x18\x06 \x03(\t\"\xc1\x01\n\rMediaMetadata\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x1d\n\x10\x64uration_seconds\x18\x03 \x01(\x01H\x00\x88\x01\x01\x12\x10\n\x03\x66ps\x18\x04 \x01(\x01H\x01\x88\x01\x01\x12\x0b\n\x03md5\x18\x05 \x01(\t\x12\x10\n\x08\x66iletype\x18\x06 \x01(\t\x12\x16\n\thas_audio\x18\x07 \x01(\x08H\x02\x88\x01\x01\x42\x13\n\x11_duration_secondsB\x06\n\x04_fpsB\x0c\n\n_has_audio\"\xa4\x01\n\nDerivative\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12)\n\x03ref\x18\x02 \x01(\x0b\x32\x1c.codex.messages.v1.ObjectRef\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x14\n\x07variant\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05\x63odec\x18\x06 \x01(\tH\x01\x88\x01\x01\x42\n\n\x08_variantB\x08\n\x06_codec\"\xce\x01\n\x0eMediaProcessed\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0f\n\x07post_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x32\n\x08metadata\x18\x04 \x01(\x0b\x32 .codex.messages.v1.MediaMetadata\x12\r\n\x05phash\x18\x05 \x01(\t\x12\x32\n\x0b\x64\x65rivatives\x18\x06 \x03(\x0b\x32\x1d.codex.messages.v1.Derivative\x12\x14\n\x0cspec_version\x18\x07 \x01(\x05\")\n\x08JobError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"m\n\x0bMediaFailed\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0f\n\x07post_id\x18\x02 \x01(\t\x12*\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x1b.codex.messages.v1.JobError\x12\x11\n\tretriable\x18\x04 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'codex.messages.v1.media_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OBJECTREF']._serialized_start=52
  _globals['_OBJECTREF']._serialized_end=95
  _globals['_PROCESSMEDIAJOB']._serialized_start=98
  _globals['_PROCESSMEDIAJOB']._serialized_end=250
  _globals['_MEDIAMETADATA']._serialized_start=253
  _globals['_MEDIAMETADATA']._serialized_end=446
  _globals['_DERIVATIVE']._serialized_start=449
  _globals['_DERIVATIVE']._serialized_end=613
  _globals['_MEDIAPROCESSED']._serialized_start=616
  _globals['_MEDIAPROCESSED']._serialized_end=822
  _globals['_JOBERROR']._serialized_start=824
  _globals['_JOBERROR']._serialized_end=865
  _globals['_MEDIAFAILED']._serialized_start=867
  _globals['_MEDIAFAILED']._serialized_end=976
# @@protoc_insertion_point(module_scope)
