# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: codex/messages/v1/tag.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from codex.messages.v1 import media_pb2 as codex_dot_messages_dot_v1_dot_media__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63odex/messages/v1/tag.proto\x12\x11\x63odex.messages.v1\x1a\x1d\x63odex/messages/v1/media.proto\"[\n\x06TagJob\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12,\n\x06sample\x18\x02 \x01(\x0b\x32\x1c.codex.messages.v1.ObjectRef\x12\x12\n\nmedia_type\x18\x03 \x01(\t\"d\n\rTagSuggestion\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x15\n\x08\x63\x61tegory\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\x0e\n\x06source\x18\x04 \x01(\tB\x0b\n\t_category\"\x88\x01\n\x0eTagSuggestions\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x35\n\x0bsuggestions\x18\x02 \x03(\x0b\x32 .codex.messages.v1.TagSuggestion\x12\x13\n\x06rating\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x0e\n\x06status\x18\x04 \x01(\tB\t\n\x07_ratingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'codex.messages.v1.tag_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TAGJOB']._serialized_start=81
  _globals['_TAGJOB']._serialized_end=172
  _globals['_TAGSUGGESTION']._serialized_start=174
  _globals['_TAGSUGGESTION']._serialized_end=274
  _globals['_TAGSUGGESTIONS']._serialized_start=277
  _globals['_TAGSUGGESTIONS']._serialized_end=413
# @@protoc_insertion_point(module_scope)
