# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from apollostorage.grpc import object_api_pb2 as apollostorage_dot_grpc_dot_object__api__pb2


class ObjectApiStub(object):
    """Client-facing object API (object-api spec, design D7/D16). Payload transfer is
    streamed with a header-then-chunks framing.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBucket = channel.unary_unary(
                '/apollostorage.grpc.ObjectApi/CreateBucket',
                request_serializer=apollostorage_dot_grpc_dot_object__api__pb2.CreateBucketRequest.SerializeToString,
                response_deserializer=apollostorage_dot_grpc_dot_object__api__pb2.BucketResponse.FromString,
                )
        self.DeleteBucket = channel.unary_unary(
                '/apollostorage.grpc.ObjectApi/DeleteBucket',
                request_serializer=apollostorage_dot_grpc_dot_object__api__pb2.DeleteBucketRequest.SerializeToString,
                response_deserializer=apollostorage_dot_grpc_dot_object__api__pb2.BucketResponse.FromString,
                )
        self.PutObject = channel.stream_unary(
                '/apollostorage.grpc.ObjectApi/PutObject',
                request_serializer=apollostorage_dot_grpc_dot_object__api__pb2.PutObjectRequest.SerializeToString,
                response_deserializer=apollostorage_dot_grpc_dot_object__api__pb2.PutObjectResponse.FromString,
                )
        self.GetObject = channel.unary_stream(
                '/apollostorage.grpc.ObjectApi/GetObject',
                request_serializer=apollostorage_dot_grpc_dot_object__api__pb2.GetObjectRequest.SerializeToString,
                response_deserializer=apollostorage_dot_grpc_dot_object__api__pb2.GetObjectResponse.FromString,
                )
        self.HeadObject = channel.unary_unary(
                '/apollostorage.grpc.ObjectApi/HeadObject',
                request_serializer=apollostorage_dot_grpc_dot_object__api__pb2.HeadObjectRequest.SerializeToString,
                response_deserializer=apollostorage_dot_grpc_dot_object__api__pb2.ObjectMetadata.FromString,
                )
        self.DeleteObject = channel.unary_unary(
                '/apollostorage.grpc.ObjectApi/DeleteObject',
                request_serializer=apollostorage_dot_grpc_dot_object__api__pb2.DeleteObjectRequest.SerializeToString,
                response_deserializer=apollostorage_dot_grpc_dot_object__api__pb2.DeleteObjectResponse.FromString,
                )
        self.ListBuckets = channel.unary_unary(
                '/apollostorage.grpc.ObjectApi/ListBuckets',
                request_serializer=apollostorage_dot_grpc_dot_object__api__pb2.ListBucketsRequest.SerializeToString,
                response_deserializer=apollostorage_dot_grpc_dot_object__api__pb2.ListBucketsResponse.FromString,
                )
        self.ListObjects = channel.unary_unary(
                '/apollostorage.grpc.ObjectApi/ListObjects',
                request_serializer=apollostorage_dot_grpc_dot_object__api__pb2.ListObjectsRequest.SerializeToString,
                response_deserializer=apollostorage_dot_grpc_dot_object__api__pb2.ListObjectsResponse.FromString,
                )


class ObjectApiServicer(object):
    """Client-facing object API (object-api spec, design D7/D16). Payload transfer is
    streamed with a header-then-chunks framing.
    """

    def CreateBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutObject(self, request_iterator, context):
        """First message MUST be `header`; every subsequent message a `chunk`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObject(self, request, context):
        """Emits a `header` message, then `chunk` messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeadObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBuckets(self, request, context):
        """Listing (served from the read model; eventually consistent).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListObjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBucket,
                    request_deserializer=apollostorage_dot_grpc_dot_object__api__pb2.CreateBucketRequest.FromString,
                    response_serializer=apollostorage_dot_grpc_dot_object__api__pb2.BucketResponse.SerializeToString,
            ),
            'DeleteBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBucket,
                    request_deserializer=apollostorage_dot_grpc_dot_object__api__pb2.DeleteBucketRequest.FromString,
                    response_serializer=apollostorage_dot_grpc_dot_object__api__pb2.BucketResponse.SerializeToString,
            ),
            'PutObject': grpc.stream_unary_rpc_method_handler(
                    servicer.PutObject,
                    request_deserializer=apollostorage_dot_grpc_dot_object__api__pb2.PutObjectRequest.FromString,
                    response_serializer=apollostorage_dot_grpc_dot_object__api__pb2.PutObjectResponse.SerializeToString,
            ),
            'GetObject': grpc.unary_stream_rpc_method_handler(
                    servicer.GetObject,
                    request_deserializer=apollostorage_dot_grpc_dot_object__api__pb2.GetObjectRequest.FromString,
                    response_serializer=apollostorage_dot_grpc_dot_object__api__pb2.GetObjectResponse.SerializeToString,
            ),
            'HeadObject': grpc.unary_unary_rpc_method_handler(
                    servicer.HeadObject,
                    request_deserializer=apollostorage_dot_grpc_dot_object__api__pb2.HeadObjectRequest.FromString,
                    response_serializer=apollostorage_dot_grpc_dot_object__api__pb2.ObjectMetadata.SerializeToString,
            ),
            'DeleteObject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteObject,
                    request_deserializer=apollostorage_dot_grpc_dot_object__api__pb2.DeleteObjectRequest.FromString,
                    response_serializer=apollostorage_dot_grpc_dot_object__api__pb2.DeleteObjectResponse.SerializeToString,
            ),
            'ListBuckets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBuckets,
                    request_deserializer=apollostorage_dot_grpc_dot_object__api__pb2.ListBucketsRequest.FromString,
                    response_serializer=apollostorage_dot_grpc_dot_object__api__pb2.ListBucketsResponse.SerializeToString,
            ),
            'ListObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListObjects,
                    request_deserializer=apollostorage_dot_grpc_dot_object__api__pb2.ListObjectsRequest.FromString,
                    response_serializer=apollostorage_dot_grpc_dot_object__api__pb2.ListObjectsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'apollostorage.grpc.ObjectApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ObjectApi(object):
    """Client-facing object API (object-api spec, design D7/D16). Payload transfer is
    streamed with a header-then-chunks framing.
    """

    @staticmethod
    def CreateBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apollostorage.grpc.ObjectApi/CreateBucket',
            apollostorage_dot_grpc_dot_object__api__pb2.CreateBucketRequest.SerializeToString,
            apollostorage_dot_grpc_dot_object__api__pb2.BucketResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apollostorage.grpc.ObjectApi/DeleteBucket',
            apollostorage_dot_grpc_dot_object__api__pb2.DeleteBucketRequest.SerializeToString,
            apollostorage_dot_grpc_dot_object__api__pb2.BucketResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutObject(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/apollostorage.grpc.ObjectApi/PutObject',
            apollostorage_dot_grpc_dot_object__api__pb2.PutObjectRequest.SerializeToString,
            apollostorage_dot_grpc_dot_object__api__pb2.PutObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/apollostorage.grpc.ObjectApi/GetObject',
            apollostorage_dot_grpc_dot_object__api__pb2.GetObjectRequest.SerializeToString,
            apollostorage_dot_grpc_dot_object__api__pb2.GetObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HeadObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apollostorage.grpc.ObjectApi/HeadObject',
            apollostorage_dot_grpc_dot_object__api__pb2.HeadObjectRequest.SerializeToString,
            apollostorage_dot_grpc_dot_object__api__pb2.ObjectMetadata.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apollostorage.grpc.ObjectApi/DeleteObject',
            apollostorage_dot_grpc_dot_object__api__pb2.DeleteObjectRequest.SerializeToString,
            apollostorage_dot_grpc_dot_object__api__pb2.DeleteObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListBuckets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apollostorage.grpc.ObjectApi/ListBuckets',
            apollostorage_dot_grpc_dot_object__api__pb2.ListBucketsRequest.SerializeToString,
            apollostorage_dot_grpc_dot_object__api__pb2.ListBucketsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apollostorage.grpc.ObjectApi/ListObjects',
            apollostorage_dot_grpc_dot_object__api__pb2.ListObjectsRequest.SerializeToString,
            apollostorage_dot_grpc_dot_object__api__pb2.ListObjectsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
